create table if not exists user_table (
    user_id bigint generated by default as identity,
    user_phone_number varchar(255),
    user_description varchar(255),
    user_email varchar(255),
    user_name varchar(255),
    user_password varchar(255),
    primary key (user_id)
)

create table if not exists attachment_table (
  attachment_id uuid default random_uuid() not null,
  attachment_content blob,
  attachment_content_type varchar(255),
  attachment_description varchar(255),
  attachment_name varchar(255),
  comment_list_creat_time varchar(255),
  user_id bigint,
  primary key (attachment_id),
  foreign key (user_id)
      references usertable
)

create table if not exists comment_table (
   comment_id uuid default random_uuid() not null,
   attachment_id uuid,
   comment_content varchar(255),
   user_name varchar(255),
   primary key (comment_id),
   foreign key (attachment_id)
       references attachment_table
)
