create table if not exists usertable (
    id bigint generated by default as identity,
    body varchar(255),
    username varchar(255),
    comment varchar(255),
    primary key (id)
);
create table if not exists attachment (
    id uuid default random_uuid() not null,
    content blob,
    content_type varchar(255),
    filename varchar(255),
    user_id bigint,
    primary key (id),
    foreign key (userinfo_id) references userinfo
);
